version: '3.7'
services:
  react-app:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - .env