version: '3.7'
services:
  react-app:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NODE_PORT=3000
      - CHOKIDAR_USEPOLLING=true